
import type { Property, UserProfile } from '@/context/app-context';

export const mockUsers: UserProfile[] = [
  {
    id: 'user-1',
    name: 'John Doe',
    email: 'john@example.com',
    profilePicture: 'https://picsum.photos/seed/user1/200/200',
  },
  {
    id: 'user-2',
    name: 'Jane Smith',
    email: 'jane@example.com',
    profilePicture: 'https://picsum.photos/seed/user2/200/200',
  },
];

export const mockProperties: Property[] = [
  {
    id: 'prop-1',
    userId: 'user-1',
    title: 'Modern Downtown Loft',
    address:
      '123 Main Street, Apt 101, Toronto, ON M5V 2N1, Canada',
    country: 'Canada',
    city: 'Toronto',
    area: 'Downtown',
    rent: 2500,
    bedrooms: 2,
    bathrooms: 2,
    hasGas: true,
    hasElectricity: true,
    phone: '123-456-7890',
    whatsapp: '1234567890',
    image: 'https://picsum.photos/seed/prop1/800/600',
  },
  {
    id: 'prop-2',
    userId: 'user-2',
    title: 'Cozy Suburban House',
    address:
      '456 Oak Avenue, Austin, TX 78704, United States',
    country: 'United States',
    city: 'Austin',
    area: 'South Congress',
    rent: 3000,
    bedrooms: 4,
    bathrooms: 3,
    hasGas: true,
    hasElectricity: true,
    phone: '098-765-4321',
    whatsapp: '0987654321',
    image: 'https://picsum.photos/seed/prop2/800/600',
  },
  {
    id: 'prop-3',
    userId: 'user-1',
    title: 'Sunny Beachfront Condo',
    address:
      '789 Beach Blvd, Cancun, Quintana Roo 77521, Mexico',
    country: 'Mexico',
    city: 'Cancun',
    area: 'Zona Hotelera',
    rent: 2200,
    bedrooms: 3,
    bathrooms: 2,
    hasGas: false,
    hasElectricity: true,
    phone: '555-123-4567',
    whatsapp: '5551234567',
    image: 'https://picsum.photos/seed/prop3/800/600',
  },
    {
    id: 'prop-4',
    userId: 'user-2',
    title: 'Spacious Family Home with Pool',
    address: '101 Pine St, Sydney, NSW 2000, Australia',
    country: 'Australia',
    city: 'Sydney',
    area: 'Bondi',
    rent: 4500,
    bedrooms: 5,
    bathrooms: 4,
    hasGas: true,
    hasElectricity: true,
    phone: '444-555-6666',
    whatsapp: '4445556666',
    image: 'https://picsum.photos/seed/prop4/800/600',
  },
  {
    id: 'prop-5',
    userId: 'user-1',
    title: 'Rustic Mountain Cabin',
    address: '23 High Alpine Rd, Interlaken, 3800, Switzerland',
    country: 'Switzerland',
    city: 'Interlaken',
    area: 'Matten bei Interlaken',
    rent: 1800,
    bedrooms: 2,
    bathrooms: 1,
    hasGas: true,
    hasElectricity: true,
    phone: '777-888-9999',
    whatsapp: '7778889999',
    image: 'https://picsum.photos/seed/prop5/800/600',
  },
];
￼Enter
